/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppUsuariosRouteImport } from './routes/app/usuarios'
import { Route as AppRemarketingRouteImport } from './routes/app/remarketing'
import { Route as AppKanbanRouteImport } from './routes/app/kanban'
import { Route as AppConfiguracoesRouteImport } from './routes/app/configuracoes'
import { Route as AppClientesRouteImport } from './routes/app/clientes'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppAgendaRouteImport } from './routes/app/agenda'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppClientesNovoRouteImport } from './routes/app/clientes.novo'
import { Route as AppChatIaRouteImport } from './routes/app/chat.ia'
import { Route as ApiSettingsChatbotEvolutionRouteImport } from './routes/api/settings/chatbot/evolution'
import { Route as ApiSettingsChatbotEducationRouteImport } from './routes/api/settings/chatbot/education'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppRemarketingRoute = AppRemarketingRouteImport.update({
  id: '/remarketing',
  path: '/remarketing',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientesNovoRoute = AppClientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppChatIaRoute = AppChatIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppChatRoute,
} as any)
const ApiSettingsChatbotEvolutionRoute =
  ApiSettingsChatbotEvolutionRouteImport.update({
    id: '/api/settings/chatbot/evolution',
    path: '/api/settings/chatbot/evolution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSettingsChatbotEducationRoute =
  ApiSettingsChatbotEducationRouteImport.update({
    id: '/api/settings/chatbot/education',
    path: '/api/settings/chatbot/education',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/chat': typeof AppChatRouteWithChildren
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/remarketing': typeof AppRemarketingRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/ia': typeof AppChatIaRoute
  '/app/clientes/novo': typeof AppClientesNovoRoute
  '/api/settings/chatbot/education': typeof ApiSettingsChatbotEducationRoute
  '/api/settings/chatbot/evolution': typeof ApiSettingsChatbotEvolutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/chat': typeof AppChatRouteWithChildren
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/remarketing': typeof AppRemarketingRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app': typeof AppIndexRoute
  '/app/chat/ia': typeof AppChatIaRoute
  '/app/clientes/novo': typeof AppClientesNovoRoute
  '/api/settings/chatbot/education': typeof ApiSettingsChatbotEducationRoute
  '/api/settings/chatbot/evolution': typeof ApiSettingsChatbotEvolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/chat': typeof AppChatRouteWithChildren
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/remarketing': typeof AppRemarketingRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/ia': typeof AppChatIaRoute
  '/app/clientes/novo': typeof AppClientesNovoRoute
  '/api/settings/chatbot/education': typeof ApiSettingsChatbotEducationRoute
  '/api/settings/chatbot/evolution': typeof ApiSettingsChatbotEvolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/api/health'
    | '/app/agenda'
    | '/app/chat'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/kanban'
    | '/app/remarketing'
    | '/app/usuarios'
    | '/app/'
    | '/app/chat/ia'
    | '/app/clientes/novo'
    | '/api/settings/chatbot/education'
    | '/api/settings/chatbot/evolution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/health'
    | '/app/agenda'
    | '/app/chat'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/kanban'
    | '/app/remarketing'
    | '/app/usuarios'
    | '/app'
    | '/app/chat/ia'
    | '/app/clientes/novo'
    | '/api/settings/chatbot/education'
    | '/api/settings/chatbot/evolution'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/api/health'
    | '/app/agenda'
    | '/app/chat'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/kanban'
    | '/app/remarketing'
    | '/app/usuarios'
    | '/app/'
    | '/app/chat/ia'
    | '/app/clientes/novo'
    | '/api/settings/chatbot/education'
    | '/api/settings/chatbot/evolution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSettingsChatbotEducationRoute: typeof ApiSettingsChatbotEducationRoute
  ApiSettingsChatbotEvolutionRoute: typeof ApiSettingsChatbotEvolutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/remarketing': {
      id: '/app/remarketing'
      path: '/remarketing'
      fullPath: '/app/remarketing'
      preLoaderRoute: typeof AppRemarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kanban': {
      id: '/app/kanban'
      path: '/kanban'
      fullPath: '/app/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clientes/novo': {
      id: '/app/clientes/novo'
      path: '/novo'
      fullPath: '/app/clientes/novo'
      preLoaderRoute: typeof AppClientesNovoRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/app/chat/ia': {
      id: '/app/chat/ia'
      path: '/ia'
      fullPath: '/app/chat/ia'
      preLoaderRoute: typeof AppChatIaRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/api/settings/chatbot/evolution': {
      id: '/api/settings/chatbot/evolution'
      path: '/api/settings/chatbot/evolution'
      fullPath: '/api/settings/chatbot/evolution'
      preLoaderRoute: typeof ApiSettingsChatbotEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/chatbot/education': {
      id: '/api/settings/chatbot/education'
      path: '/api/settings/chatbot/education'
      fullPath: '/api/settings/chatbot/education'
      preLoaderRoute: typeof ApiSettingsChatbotEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppChatRouteChildren {
  AppChatIaRoute: typeof AppChatIaRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatIaRoute: AppChatIaRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppClientesRouteChildren {
  AppClientesNovoRoute: typeof AppClientesNovoRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesNovoRoute: AppClientesNovoRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppChatRoute: typeof AppChatRouteWithChildren
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppRemarketingRoute: typeof AppRemarketingRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppChatRoute: AppChatRouteWithChildren,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppRemarketingRoute: AppRemarketingRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSettingsChatbotEducationRoute: ApiSettingsChatbotEducationRoute,
  ApiSettingsChatbotEvolutionRoute: ApiSettingsChatbotEvolutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
