/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppUsuariosRouteImport } from './routes/app/usuarios'
import { Route as AppRemarketingRouteImport } from './routes/app/remarketing'
import { Route as AppKanbanRouteImport } from './routes/app/kanban'
import { Route as AppConfiguracoesRouteImport } from './routes/app/configuracoes'
import { Route as AppClientesRouteImport } from './routes/app/clientes'
import { Route as AppAgendaRouteImport } from './routes/app/agenda'
import { Route as AppClientesNovoRouteImport } from './routes/app/clientes.novo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppRemarketingRoute = AppRemarketingRouteImport.update({
  id: '/remarketing',
  path: '/remarketing',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesNovoRoute = AppClientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/remarketing': typeof AppRemarketingRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/novo': typeof AppClientesNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/remarketing': typeof AppRemarketingRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app': typeof AppIndexRoute
  '/app/clientes/novo': typeof AppClientesNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/remarketing': typeof AppRemarketingRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/novo': typeof AppClientesNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/kanban'
    | '/app/remarketing'
    | '/app/usuarios'
    | '/app/'
    | '/app/clientes/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/kanban'
    | '/app/remarketing'
    | '/app/usuarios'
    | '/app'
    | '/app/clientes/novo'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/kanban'
    | '/app/remarketing'
    | '/app/usuarios'
    | '/app/'
    | '/app/clientes/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/remarketing': {
      id: '/app/remarketing'
      path: '/remarketing'
      fullPath: '/app/remarketing'
      preLoaderRoute: typeof AppRemarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kanban': {
      id: '/app/kanban'
      path: '/kanban'
      fullPath: '/app/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/novo': {
      id: '/app/clientes/novo'
      path: '/novo'
      fullPath: '/app/clientes/novo'
      preLoaderRoute: typeof AppClientesNovoRouteImport
      parentRoute: typeof AppClientesRoute
    }
  }
}

interface AppClientesRouteChildren {
  AppClientesNovoRoute: typeof AppClientesNovoRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesNovoRoute: AppClientesNovoRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppRemarketingRoute: typeof AppRemarketingRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppRemarketingRoute: AppRemarketingRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
